packagegroup-container: require ipv6 for podman
The recipe *podman* requires the distro feature *ipv6*. Using a distro
without it causes the build of *packagegroup-container* fails, even if
*packagegroup-podman* is not used:

    ERROR: Nothing RPROVIDES 'podman' (but /build/../work/layers-3rdparty/meta-virtualization/recipes-core/packagegroups/packagegroup-container.bb RDEPENDS on or otherwise requires it)
    podman was skipped: missing required distro feature 'ipv6' (not in DISTRO_FEATURES)
    NOTE: Runtime target 'podman' is unbuildable, removing...
    Missing or unbuildable dependency chain was: ['podman']
    NOTE: Runtime target 'packagegroup-docker' is unbuildable, removing...
    Missing or unbuildable dependency chain was: ['packagegroup-docker', 'podman']

Signed-off-by: Jörg Sommer <joerg.sommer@navimatix.de>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>