libvirt: fix polkit file conflict
The switch to RPM4 and dnf results in this error during rootfs construction:

  Error: Transaction check error:
    file /usr/share/polkit-1/rules.d conflicts between attempted installs of libvirt-1.3.5-r0.13.core2_64 and polkit-0.113-r0.9.core2_64

We can temporarily work around it by instructing RPM to not package/process
the dirfiles.

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>