docker: move docker.init back to files directory to use it from docker-moby
* it was moved for some reason in:
  http://git.yoctoproject.org/cgit/cgit.cgi/meta-virtualization/commit/?id=929372946aeb85953d1ca6acc428d73fbac52a56

  but docker-moby uses it as well and now started to fail with:
  ERROR: docker-moby-19.03.12+git9dc6525e6118a25fab2be322d1914740ea842495-r0
  do_fetch: Fetcher failure: Unable to find file file://docker.init
  anywhere. ..

Signed-off-by: Martin Jansa <martin.jansa@lge.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>