xen: fix build race condition
It has been reported that xen can fail to build with the
following error:

| In file included from xsm/flask/ss/services.c:46:
| ./xsm/flask/include/avc.h:18:10: fatal error: av_permissions.h: No
such file or directory
|    18 | #include "av_permissions.h"
|       |          ^~~~~~~~~~~~~~~~~~

This fix has been proposed upstream:
https://lore.kernel.org/xen-devel/20230120133626.55680-1-anthony.perard@citrix.com/T/#u

It doesn't break our build, so we include it for stress testing.

Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>