openvswitch: add missing python modules to execute ovs-test program
ovs-test program requires python-twisted and ovstest python
modules to execute successfully. The changes fix below
errors:

-- snip --
root@qemux86:~# ovs-test
Traceback (most recent call last):
  File "/usr/bin/ovs-test", line 31, in <module>
    import twisted
ImportError: No module named twisted
root@qemux86:~# ovs-test
Traceback (most recent call last):
  File "/usr/bin/ovs-test", line 33, in <module>
    import ovstest.args as args
ImportError: No module named ovstest.args
root@qemux86:~#
-- snip --

Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>