openvswitch: Fix rootfs creation errors
error: file /var/run from install of openvswitch-2.1.3-r0.x86_64
    conflicts with file from package base-files-3.0.14-r89.ubinux_x86_64

Signed-off-by: Dai Caiyun <daicy.fnst@cn.fujitsu.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>