protobuf: fix ptest compile errors
While buiding protobuf ptest on Centos 6.4, the build
failed with errors:

...libprotobuf.so: undefined reference to `memcpy@GLIBC_2.14'

This is due to protobuf.pc still contains /usr/lib64
as libdir which are not good for cross compiling.
Replace it with proper sysroot path.

Signed-off-by: Zibo Zhao <Zibo.Zhao@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>