fs-perms-nagios.txt: add perms conf file
Add this perms conf file to avoid do_rootfs failure due to conflicts
among nagios packages.

The error message is like below.

Error: Transaction check error:
  file /etc/nagios conflicts between attempted installs of \
  nagios-core-4.0.8-r0.core2_64 and nagios-nrpe-plugin-2.15-r0.core2_64

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>