k3s: update to 1.24.3
We bumping to 1.24.x, along with the k3s changes, we update our
dependencies to allow a vendored build.

Dependencies were gathered via: go list -m all  | sort | uniq > mod.all

And then processed to generate the SRC_URI fetches and relocations into
the build.

We also change our TAGS to avoid two different errors. btrfs
build restrictions:

   package command-line-arguments
           imports github.com/k3s-io/k3s/pkg/cli/agent
           imports github.com/k3s-io/k3s/pkg/agent
           imports github.com/k3s-io/k3s/pkg/agent/config
           imports github.com/k3s-io/k3s/pkg/containerd
           imports github.com/containerd/containerd/snapshots/btrfs/plugin:
   build constraints exclude all Go files in github.com/k3s-io/containerd@v1.5.13-k3s1/snapshots/btrfs/plugin

And ctrd, which leads to the following (which is also
found on non Yocto / non-cross build k3s builds):

  # github.com/containerd/containerd/pkg/cri/server
  ../../go/pkg/mod/github.com/k3s-io/containerd@v1.5.13-k3s1/pkg/cri/server/instrumented_service.go:36:9: cannot use &instrumentedService{?} (value of type *instrumentedService) as type grpcServices in return statement:
        *instrumentedService does not implement grpcServices (missing ListPodSandboxStats method)
  ../../go/pkg/mod/github.com/k3s-io/containerd@v1.5.13-k3s1/pkg/cri/server/service.go:156:9: cannot use c (variable of type *criService) as type CRIService in return statement:
        *criService does not implement CRIService (missing ListPodSandboxStats method)

Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>