openvswitch: uprev from v2.17.0-30-g2404d4536 to v2.17.1
commits short log:
41bb202fb (tag: v2.17.1) Set release date for 2.17.1.
8f42d4f59 NEWS: Highlight libopenvswitch API change caused by UB fixes.
14301b3a3 netdev-offload-tc: Check for ct_state flag combinations that are not offloadable.
3a2eef792 python: idl: Set cond_changed to true if condition change requested.
d05ccf288 dpif-netdev: Fix dp_netdev_get_pmd() function getting correct core_id.
79e291f98 alb.at: Add tests for cross-numa polling.
9c3b74fb2 dpif-netdev: Fix PMD auto load balance with pmd-rxq-isolate.
8580ff9dd pmd.at: Add tests for multi non-local numa pmds.
6bf4eeddb dpif-netdev: Fix non-local numa selection for more than two numas.
c41434b3b dpif-netdev: Fix typo in function name.
e0aa5e132 python: idl: Set cond_changed to false if last id is zero.
8da40d31c ofproto-dpif-xlate: Fix NULL pointer dereference in xlate_normal().
63a903ab4 ofproto/ofproto-dpif: Fix dpif_type for userspace tunnels.
14d54eb8b sset: add SHORT version of SAFE loop macros.
f0e63b115 sparse: bump recommended version and include headers.
70b87cf72 idlc: support short version of SAFE macros.
3777ed90c rculist: use multi-variable helpers for loop macros.
bb52e9beb hindex: remove the next variable in safe loops.
7d6cbfa24 hindex: use multi-variable iterators.
97ad96b63 cmap: use multi-variable iterators.
cd62fda22 hmap: use short version of safe loops if possible.
d56bfd752 hmap: implement UB-safe hmap pop iterator.
e2c835486 hmap: use multi-variable helpers for hmap loops.
897d6647e list: use short version of safe loops if possible.
979a9eb5b list: use multi-variable helpers for list loops.
6bacf802c util: add helpers to overload SAFE macro.
f127123d6 util: add safe multi-variable iterators.
38e73f0b6 util: add multi-variable loop iterator macros.
e91edf456 ovsdb: raft: Fix inability to read the database with DNS host names.

The ptest results BEFORE uprev:
ERROR: 2340 tests were run,
30 failed unexpectedly.
65 tests were skipped.
failed cases:
10 11 12 13 14 15 16 17 18 462 769 785 786 787 788 791 792 793 1024 1180 1181
1182 1183 1184 1185 1290 1291 2387 2391 2394

The ptest results AFTER uprev:
ERROR: 2343 tests were run,
30 failed unexpectedly.
65 tests were skipped.
failed cases:
10 11 12 13 14 15 16 17 18 462 769 785 786 787 788 791 792 793 1025 1183 1184
1185 1186 1187 1188 1293 1294 2390 2394 2397

Signed-off-by: He Zhe <zhe.he@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>