libvirt: fix build failure, failing QA check
  The build is failing due to a failing QA check:

   ERROR: libvirt-1.3.5-r0 do_package_qa: QA Issue: /usr/lib/libvirt/ptest/tests/tests/check-file-access.pl
   contained in package libvirt-ptest requires /usr/bin/perl,
   but no providers found in RDEPENDS_libvirt-ptest? [file-rdeps]

Signed-off-by: Chunrong Guo <chunrong.guo@nxp.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>