python3-fastentrypoints: add missing setuptools RDEPENDS
Add missing setuptools RDEPENDS to fix below error:
 # python3
Python 3.8.2 (default, Apr 27 2020, 08:51:00)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fastentrypoints
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/lib64/python3.8/site-packages/fastentrypoints.py", line 39, in <module>
from setuptools.command import easy_install
ModuleNotFoundError: No module named 'setuptools'

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>