go-systemd: Fix QA dependency problem
ERROR: go-systemd-4+gitb4a58d95188dd092ae20072bac14cece0e67c388-r0
do_package_qa: QA Issue:
/usr/local/go/src/github.com/coreos/go-systemd/test contained in
package go-systemd requires /bin/bash, but no providers found in
RDEPENDS_go-systemd? [file-rdeps]

Resolved with proper dependency to bash.

Signed-off-by: Jason Wessel <jason.wessel@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>