libvirt: fix installed-vs-shipped QA error
In commit [1], upstream added sysusers config file for qemu & kvm user/groups,
the install dir is "install_dir: prefix / 'lib' / 'sysusers.d'".

In commit [2], Yocto created an empty file libvirt-qemu.conf to override
sysusers config file which is added by commit [1]

While usrmerge not in DISTRO_FEATURES, nonarch_base_libdir does not match
install_dir and trigger an installed-vs-shipped QA error
...
ERROR: QA Issue: libvirt: Files/directories were installed but not shipped in any package:
  /usr/lib/sysusers.d
  /usr/lib/sysusers.d/libvirt-qemu.conf
Please set FILES such that these items are packaged. Alternatively if they are unneeded, avoid installing them or delete them within do_install.
libvirt: 2 installed and not shipped files. [installed-vs-shipped]
...

Use nonarch_libdir to intead of nonarch_base_libdir to match the install dir
in commit [1]

[1] https://github.com/libvirt/libvirt/commit/a2c3e390f7bedf36f4ddc544d09fe3b8772c5c6f
[2] https://git.yoctoproject.org/meta-virtualization/commit/?id=8138d9cc7e0c31171230110db0cfa881c46a821b

Suggested-by: Chen Qi <Qi.Chen@windriver.com>
Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>