podman: require catatonit
Alternatively, we could add it to RRECOMMENDS. But I would say, given
its name, managing pods is part of podman's core functionality and that
requires catatonit, which is currently only pulled in for the ptest:

root@qemux86-64:~# podman pod create
Error: building local pause image: finding pause binary: exec: "catatonit": executable file not found in $PATH

Signed-off-by: Patrick Wicki <patrick.wicki@siemens.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>