python3-fastentrypoints: add the missing rdepends
Add the missing rdepends to fix below error:
 # python3
 [snip]
 >>> import fastentrypoints
 [snip]
 ModuleNotFoundError: No module named 'pickle'

Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>