linux-yocto_virtualization.inc: parse MAJOR.MINOR version from PV not PREFERRED_VERSION
* it was introduced in:
  https://git.yoctoproject.org/meta-virtualization/commit/?id=a940a0e873f9163d4585555b3f3d38e99400d237
  but it doesn't work well when PREFERRED_VERSION is set to e.g. "6.6.%",
  you remove the '%' but not the trailing dot, causing:

  ERROR: Nothing PROVIDES 'yocto-cfg-fragments-6.6.-native'. Close matches:
    yocto-cfg-fragments-6.10-native
    yocto-cfg-fragments-6.6
    yocto-cfg-fragments-6.6-native

Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>