nagios-core/nagios-nrpe: use update-alternatives for /var/nagios
fix below error:
Error: Transaction check error:
  file /var/nagios from install of nagios-core-4.4.3-r0.core2_64 conflicts with file from package nagios-nrpe-daemon-3.2.1-r0.core2_64

Signed-off-by: Changqing Li <changqing.li@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>