irqbalance: bump SRCREV to latest
* remove the incorrect comment about SRCREV being 1.7.0
* and add +git because the old SRCREV wasn't matching
  with 1.8.0 tag as well

* add -Wno-error=format-security to work around build failures with newer ncurses-6.3 like:
  | ../git/ui/ui.c:45:32: error: format not a string literal and no format arguments [-Werror=format-security]
  |    45 |         mvprintw(LINES - 1, 0, footer);
  |       |                                ^~~~~~

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>