libvirt: add 'wireshark' packageconfig
libvirt by default has '--with-wireshark-dissector' set to
'check'. Therefor if wireshark is built before vs after libvirt this
will result in a potentially unexpected difference in how libvirt is
configured. Additionally the build of libvirt with wireshark
capabilities enabled is currently broken and thus if attempted will
result in the error:

fatal error: ws_symbol_export.h: No such file or directory

To prevent the random configuration of libvirt with respect to
wireshark we add a new packageconfig for wireshark.

NOTE that the wireshark recipe is currently incomplete so this new
packageconfig will result in a build failure if used, until wireshark
is updated to build libwsutil.

Signed-off-by: Mark Asselstine <mark.asselstine@windriver.com>