libvirt: update to 1.1.1
Updating to the 1.1.1 libvirt release. Changes from the 1.0.3 recipe include
a fix/workaround for the:

 ../src/.libs/libvirt.so: undefined reference to `virNetTLSInit'

That is seen on some machines. The current fix is to explicilty link against
the library which provides the definition. A smarter fix via libtool may
be possible, but was elusive at the time of writing this patch.

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>