dev86: fix ldflags QA issue by passing LDFLAGS
ERROR: dev86-0.16.21-r0 do_package_qa: QA Issue: File /usr/lib/bcc/unproto in package dev86 doesn't have GNU_HASH (didn't pass LDFLAGS?)
File /usr/lib/bcc/bcc-cpp in package dev86 doesn't have GNU_HASH (didn't pass LDFLAGS?)
File /usr/lib/bcc/copt in package dev86 doesn't have GNU_HASH (didn't pass LDFLAGS?)
File /usr/lib/bcc/bcc-cc1 in package dev86 doesn't have GNU_HASH (didn't pass LDFLAGS?)
File /usr/bin/ld86 in package dev86 doesn't have GNU_HASH (didn't pass LDFLAGS?)
File /usr/bin/ar86 in package dev86 doesn't have GNU_HASH (didn't pass LDFLAGS?)
File /usr/bin/size86 in package dev86 doesn't have GNU_HASH (didn't pass LDFLAGS?)
File /usr/bin/nm86 in package dev86 doesn't have GNU_HASH (didn't pass LDFLAGS?)
File /usr/bin/as86 in package dev86 doesn't have GNU_HASH (didn't pass LDFLAGS?)
File /usr/bin/objdump86 in package dev86 doesn't have GNU_HASH (didn't pass LDFLAGS?)
File /usr/bin/bcc in package dev86 doesn't have GNU_HASH (didn't pass LDFLAGS?) [ldflags]
ERROR: dev86-0.16.21-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>