cloud-init: fix usrmerge QA issue
* backport a fix from 23.2 version (notice that the recipe claims to be:
  v23.2.2+git, but the commit in master-next which updated PV only changed
  the branch name, not the SRCREV, so it's still 23.1 and missing this fix

  cloud-init/v23.2.2+git/git $ git describe --tags
  23.1-53-g57752970e

* fixes:
  ERROR: cloud-init-v23.2.2+git-r0 do_package_qa: QA Issue: cloud-init package is not obeying usrmerge distro feature. /lib should be relocated to /usr. [usrmerge]

  caused by udev rules:
  $ find cloud-init/v23.2.2+git/image/lib/
  cloud-init/v23.2.2+git/image/lib/
  cloud-init/v23.2.2+git/image/lib/udev
  cloud-init/v23.2.2+git/image/lib/udev/rules.d
  cloud-init/v23.2.2+git/image/lib/udev/rules.d/66-azure-ephemeral.rules

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>